USER_NAME_REGEX = r"[^\x00-\x7F]+"

CHANNEL_BOT_LOGS: str = "bot-logs"
CHANNEL_BOT_TESTING: str = "bot-testing"
CHANNEL_GENERAL: str = "general"
CHANNEL_GAMING: str = "gaming"
CHANNEL_HOTS: str = "hots"
CHANNEL_MOD_CHAT: str = "mod-chat"
CHANNEL_VIP_CHAT: str = "vip-chat"

DB_CLEVERBOT: str = "cleverbot"
DB_SERVER_ID: str = "serverid"
DB_WEATHER: str = "weather"

ROLE_ADMIN: str = "admin"
ROLE_MODERATOR: str = "moderator"
ROLE_MODERATOR_PERMS: str = "moderator_perms"
ROLE_NEW: str = "new"
ROLE_STREAMING: str = "streaming"
ROLE_VIP: str = "vip"
ROLE_VIP_PERMS: str = "vip_perms"